=== api-evangelist/1factory/json-schema/1factory-issue-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/1factory/refs/heads/main/json-schema/1factory-issue-schema.json",
  "title": "Issue",
  "description": "Issue schema from 1Factory API",
  "type": "object",
  "properties": {
    "ID": {
      "$ref": "#/components/schemas/ID"
    },
    "number": {
      "type": "number",
      "example": 1234,
      "description": "The reference number for the NCR, Complaint, or CAPA"
    },
    "part_number": {
      "$ref": "#/components/schemas/part_number"
    },
    "rev": {
      "$ref": "#/components/schemas/rev"
    },
    "part_description": {
      "$ref": "#/components/schemas/part_description"
    },
    "customer_name": {
      "$ref": "#/components/schemas/customer_name"
    },
    "customer_ident": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom identifier for customer NCRs (ex. Customer PO #)",
      "example": "PO-1234"
    },
    "supplier_name": {
      "$ref": "#/components/schemas/supplier_name"
    },
    "supplier_ident": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom identifier for supplier NCRs (ex. Supplier Lot #)",
      "example": "123456"
    },
    "type": {
      "type": "string",
      "maxLength": 255,
      "description": "Type of NCR",
      "example": "Rcvg.",
      "enum": [
        "Rcvg.",
        "Mfg.",
        "Field",
        "Cust.",
        "Devn."
      ]
    },
    "mfg_insp_ident_1": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom primary identifier for manufacturing inspection identifiers. (ex. Job #)",
      "example": "job-20240003"
    },
    "mfg_insp_ident_2": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom secondary identifier for manufacturing inspection identifiers. (ex. PO #)",
      "example": "po-20240065"
    },
    "rec_insp_ident_1": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom primary identifier for receiving inspection identifiers. (ex. Job #)",
      "example": "job-20240003"
    },
    "rec_insp_ident_2": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Your Organization's custom secondary identifier for receiving inspection identifiers. (ex. PO #)",
      "example": "po-20240065"
    },
    "lot_quantity": {
      "type": "number",
      "nullable": false,
      "description": "The number of parts in the lot of the NCR",
      "example": 100
    },
    "inspection_quantity": {
      "type": "number",
      "nullable": false,
      "description": "The number of parts in the lot that were inspected as part of the NCR",
      "example": 10
    },
    "defective_quantity": {
      "type": "number",
      "nullable": false,
      "description": "The number of parts rejected as part of the NCR",
      "example": 3
    },
    "impact": {
      "type": "string",
      "description": "Business impact of the NCR",
      "example": "LOW",
      "enum": [
        "LOW",
        "MEDIUM",
        "HIGH"
      ]
    },
    "detected_at": {
      "type": "string",
      "nullable": true,
      "description": "Where the problem for the NCR was detected.",
      "example": "Final Inspection"
    },
    "problem_type": {
      "type": "string",
      "nullable": true,
      "description": "A simple description of the problem.",
      "example": "Out-of-spec"
    },
    "root_cause": {
      "type": "string",
      "nullable": true,
      "description": "The root cause of the problem.",
      "example": "Machining Error"
    },
    "caused_by": {
      "type": "string",
      "nullable": true,
      "description": "The department or group that caused the problem.",
      "example": "Engineering"
    },
    "problem_summary": {
      "type": "string",
      "nullable": true,
      "maxLength": 255,
      "description": "Problem summary of the NCR.",
      "example": "Manufacturing defect"
    },
    "total_cost": {
      "type": "number",
      "nullable": true,
      "description": "Cost of the NCR",
      "example": 1000.0
    },
    "status": {
      "type": "string",
      "description": "Status of the NCR",
      "example": "OPEN",
      "enum": [
        "OPEN",
        "CLOSED"
      ]
    },
    "task_status": {
      "type": "string",
      "nullable": false,
      "description": "Status of all tasks on NCR.",
      "example": "OPEN",
      "enum": [
        "N/A",
        "OPEN",
        "CLOSED"
      ]
    },
    "task_count": {
      "type": "number",
      "nullable": false,
      "description": "Number of tasks for the NCR.",
      "example": 3
    },
    "owner": {
      "$ref": "#/components/schemas/owner"
    },
    "created_by_name": {
      "$ref": "#/components/schemas/created_by_username"
    },
    "created_on": {
      "$ref": "#/components/schemas/created_on"
    },
    "updated_on": {
      "$ref": "#/components/schemas/updated_on"
    },
    "closed_on": {
      "$ref": "#/components/schemas/closed_on"
    }
  }
}

=== api-evangelist/1factory/examples/1factory-issue-example.json
{
  "ID": "abc123",
  "number": 1234,
  "part_number": "PART-001",
  "rev": "example-value",
  "part_description": "This is an example description.",
  "customer_name": "Example Item",
  "customer_ident": "PO-1234",
  "supplier_name": "Example Item",
  "supplier_ident": "123456",
  "type": "Rcvg.",
  "mfg_insp_ident_1": "job-20240003",
  "mfg_insp_ident_2": "po-20240065",
  "rec_insp_ident_1": "job-20240003",
  "rec_insp_ident_2": "po-20240065",
  "lot_quantity": 100,
  "inspection_quantity": 10,
  "defective_quantity": 3,
  "impact": "LOW",
  "detected_at": "Final Inspection",
  "problem_type": "Out-of-spec",
  "root_cause": "Machining Error",
  "caused_by": "Engineering",
  "problem_summary": "Manufacturing defect",
  "total_cost": 1000.0,
  "status": "OPEN",
  "task_status": "OPEN",
  "task_count": 3,
  "owner": "example-value",
  "created_by_name": "Example Item",
  "created_on": "example-value",
  "updated_on": "example-value",
  "closed_on": "example-value"
}
